export const ERR = {
  INVALID_A: 'ERR_INVALID_A',
  INVALID_B: 'ERR_INVALID_B',
  CRAMER_DIM: 'ERR_CRAMER_DIM',
  SINGULAR: 'ERR_SINGULAR',
  ZERO_DIAG: 'ERR_ZERO_DIAG',
  NOT_DIAG_DOM_JACOBI: 'ERR_NOT_DIAG_DOM_JACOBI',
  NOT_DIAG_DOM_SEIDEL: 'ERR_NOT_DIAG_DOM_SEIDEL',
  NO_SOLUTION: 'ERR_NO_SOLUTION',
};
